name: Build and Push Nextcloud with ffmpeg

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Nextcloud upstream version
        id: ncver
        run: |
          VERSION=$(docker run --rm nextcloud:apache /usr/src/nextcloud/occ --no-warnings status | grep -w versionstring | awk '{print $3}')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Check if version already exists in GHCR
        id: check
        run: |
          if docker manifest inspect ghcr.io/${{ github.repository_owner }}/nextcloud-ffmpeg:${{ steps.ncver.outputs.version }} > /dev/null 2>&1; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Stop if version already exists
        if: steps.check.outputs.exists == 'true'
        run: |
          echo "Image for version ${{ steps.ncver.outputs.version }} already exists. Skipping build."
          exit 0

      - name: Build and push image
        if: steps.check.outputs.exists == 'false'
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/nextcloud-ffmpeg:latest
            ghcr.io/${{ github.repository_owner }}/nextcloud-ffmpeg:${{ steps.ncver.outputs.version }}
